In [1]:
# Import dependencies
import sqlite3
import pandas as pd

In [2]:
# get csv to a df
file = pd.read_csv('./Resources/mockData2015.csv')
file.head()

,ID,url,entidad,calle,colonia,municipio,codigo_postal,grupo,tipo,m2Terreno,m2Construccion,recamaras,banos,estacionamiento,pisos,cuotaMantto,precio
0,3916060329,http://www.guiadinmuebles.com/venta/departamen...,Ciudad de Mexico,Encarnación Ortíz No. 1860,Ampliación Cosmopolita,Azcapotzalco,2601.0,Habitacional,Departamento,62.0,62.0,2.0,1.5,0.0,1,1536854,1536854.0
1,4708398404,http://www.guiadinmuebles.com/venta/departamen...,Ciudad de Mexico,Encarnación Ortíz No. 1860,Ampliación Cosmopolita,Azcapotzalco,2601.0,Habitacional,Departamento,62.0,62.0,2.0,1.5,0.0,1,NaN,1536854.0
2,998097431,http://www.guiadinmuebles.com/venta/departamen...,Ciudad de Mexico,\r\nAmpliación Del Gas ...,Ampliación Del Gas,Azcapotzalco,2601.0,Habitacional,Departamento,78.0,78.0,NaN,NaN,0.0,1,185,1850000.0
3,331196605,http://www.guiadinmuebles.com/venta/departamen...,Ciudad de Mexico,\r\nAmpliación Del Gas ...,Ampliación Del Gas,Azcapotzalco,2601.0,Habitacional,Departamento,64.0,64.0,NaN,NaN,0.0,1,17,1700000.0
4,7530087259,http://www.guiadinmuebles.com/venta/departamen...,Ciudad de Mexico,"\r\nAmpliación del gas, Azcapotzalco, Distrito...",Ampliación Del Gas,Azcapotzalco,2601.0,Habitacional,Departamento,77.0,65.0,NaN,2.0,0.0,1,NaN,1700000.0

In [3]:
# connect to database
conn = sqlite3.connect('./Resources/finalData.db')
c = conn.cursor()

In [4]:
# create tables in databse

c.execute('''SELECT count(name) FROM sqlite_master WHERE type='table' AND name='Inmuebles' ''')

#if the count is 1, then table exists
if c.fetchone()[0]==1: 
    print('Table exists.')
else:
    print('Table does not exist.')
    columns = 'id integer, url string, entidad string, calle string, colonia string, \
        municipio string, codigo_postal string, grupo string,tipo string,m2Terreno float,m2Construccion float, \
        recamaras integer,banos integer,estacionamiento integer, pisos integer,cuotaMantto integer,precio float'
    queryCreate = f"CREATE TABLE Inmuebles ({columns})"
    c.execute(queryCreate)

Table exists.

In [11]:
df = pd.read_sql_query("SELECT * from Inmuebles", conn)
df.head()

ProgrammingError: Cannot operate on a closed database.

In [10]:
# write the data to a sqlite table
file.to_sql("Inmuebles", conn, if_exists='append', index = False)
conn.close()